name: Deploy

on:
  release:
    types:
      - "published"

jobs:
  build-binary:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install Dependencies
        run: go get .

      - name: Build
        run: go build -ldflags="-s -w" -o bin/tmplts

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: go_binary
          path: bin/tmplts
  
  publish-binary:
    runs-on: ubuntu-latest
    needs: build-binary
    defaults:
      run:
        working-directory: ./npm
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/
          scope: "@ev-the-dev"

      - name: Download Binary
        uses: actions/download-artifact@v4
        with:
          name: go_binary
          path: npm/tmplts

      - name: Publish to NPM Registry
        run: |
          npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
