name: Deploy

on:
  # release:
  #   types:
  #     - "published"
  pull_request:
    branches: [ "main" ]

jobs:
  build-binary:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install Dependencies
        run: go get .

      - name: Build
        run: go build -o bin/tmplts

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: go_binary
          path: bin/tmplts
  
  publish-binary:
    runs-on: ubuntu-latest
    needs: build-binary
    defaults:
      run:
        working-directory: ./npm
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://npm.pkg.github.com
          scope: "@ev-the-dev"

      - name: Download Binary
        uses: actions/download-artifact@v4
        with:
          name: go_binary

      - name: Print Dir Contents
        run: |
          pwd
          ls -aL ../
          ls -aL
